name: Cancel Stale Runs

on: [pull_request]

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          workflow_id: linux.yml,macos.yaml
          access_token: ${{ github.token }}
